FromDoppler/doppler-jobs

- Doppler.Jobs.Server/Doppler.Service.Job.Server.csproj
- Doppler.Jobs.Server/Program.cs
- Doppler.Jobs.Server/Properties/launchSettings.json
- Doppler.Jobs.Server/Startup.cs
- Doppler.Jobs.Server/appsettings.json
- Doppler.Sap.Job.Test/Integration/DopplerSapJobIntegrationTests.cs
- Doppler.Sap.Job/DopplerSapJob.cs
Add An Serilog logger [link](https://github.com/serilog/serilog/wiki/Getting-Started)
Could you review it?
> Add Serilog logger file

- Doppler.Jobs.Server/Program.cs
- Doppler.Jobs.Server/Startup.cs
- Doppler.Sap.Job.Test/DopplerCurrencyServiceTests.cs
- Doppler.Sap.Job.Test/HelperExtension.cs
- Doppler.Sap.Job/DopplerCurrencyService/DopplerCurrencyService.cs
Add more test when the services return and exception when url is invalid or json is not correct
- DopplerCurrencyService_ShouldBeException_WhenUrlIsInvalid()
- DopplerCurrencyService_ShouldBeException_WhenJsonContentIsInvalid()
Could you review it?
> Doppler.Currency.Services - Catch exception when creates URL and get JSON data

- Doppler.Jobs.Server/Doppler.Service.Job.Server.csproj
- Doppler.Jobs.Server/Properties/launchSettings.json
- Doppler.Jobs.Server/Startup.cs
- Doppler.Jobs.Server/appsettings.json
- Doppler.Sap.Job.Test/Integration/DopplerSapJobIntegrationTests.cs
- Doppler.Sap.Job/Database/DopplerRepository.cs
- Doppler.Sap.Job/Database/Entities/UserBilling.cs
- Doppler.Sap.Job/Database/IDopplerRepository.cs
- Doppler.Sap.Job/Doppler.Sap.Job.Service.csproj
- Doppler.Sap.Job/DopplerSapJob.cs
- Doppler.Sap.Job/Settings/DopplerRepositorySettings.cs
Send data to SAP with information getting from Doppler database
- Add Dapper micro ORM
- Add connectionString as SercretKey
- Create SQL consult to get data
- Create an update SQL sentence to update with Doppler.Currency data
- Create service to send data of billing to SAP system
> Add Doppler Database connection

- build-n-publish.sh
> Fix publish script

- CrossCutting/CrossCutting.csproj
- CrossCutting/DopplerSapService/Entities/UserBilling.cs
- CrossCutting/TimeZoneHelper.cs
- DopplerBillingJob/Database/DbConnectionFactory.cs
- DopplerBillingJob/Database/DopplerRepository.cs
- DopplerBillingJob/Database/IDbConnectionFactory.cs
- DopplerBillingJob/DopplerBillingJob.cs
- DopplerBillingJob/Settings/DopplerBillingJobSettings.cs
- DopplerBillingJob/Settings/DopplerRepositorySettings.cs
- DopplerJobTest/Doppler.Jobs.Test.csproj
- DopplerJobTest/Integration/DopplerBillingJobTests.cs
- DopplerJobsServer/Startup.cs
- DopplerJobsServer/appsettings.json
Doppler Billing Job should be executed one day per month then the Job executes the next six stored procedures with Dapper for send user billing dato to SAP system:
[dbo].[SAP_CM_GB_BISIDE_ARG]
[dbo].[SAP_CM_GB_BISIDE_USD]
[dbo].[SAP_CM_GB_DD_USD]
[dbo].[SAP_GB_BISIDE_ARG]
[dbo].[SAP_GB_BISIDE_USD]
[dbo].[SAP_GB_DD_ARG]
Can you Review It?
> Billing Job - Add Stored Procedures

- Dockerfile
- Doppler.Database/DbConnectionFactory.cs
- Doppler.Database/Doppler.Database.csproj
- Doppler.Database/IDbConnectionFactory.cs
- Doppler.Jobs.sln
- DopplerBillingJob/Database/DopplerRepository.cs
- DopplerBillingJob/Doppler.Billing.Job.csproj
- DopplerCurrencyJob/Doppler.Currency.Job.csproj
- DopplerJobTest/Doppler.Jobs.Test.csproj
- DopplerJobsServer/Dockerfile
- DopplerJobsServer/Startup.cs
- DopplerJobsServer/appsettings.json
I created a new project in Doppler Jobs, with this change we can use the Doppler database in any Jobs for example Currency
Can you review it?
> Doppler jobs - Add Database project

- Dockerfile
Copies from https://github.com/MakingSense/doppler-mailer-system/pull/185
Copied from MakingSense/doppler-forms@48262e9
thanks, @andresmoschini and @elsupergomez
> internal: accept TLSv1 to fix connection with QA and INT environments

- CrossCutting/DopplerSapService/DopplerSapService.cs
- DopplerBillingJob/DopplerBillingJob.cs
- DopplerCurrencyJob/DopplerCurrencyJob.cs
- DopplerJobsServer/appsettings.QA.json
- DopplerJobsServer/appsettings.json
- DopplerJobsServer/appsettings.prod.json
Change the ur for Doppler Currency
> Change Url for Doppler Currency

- CrossCutting/DopplerSapService/DopplerSapService.cs
- DopplerJobsServer/appsettings.json
We were having the same issue as the Billing Request Job.
I'm also modifying the IP for the Doppler.Sap service to avoid sending wrong data into production.
This is already tested in the server and working fine.
> Fix Currency Job issue

- .dependabot/config.yml
- DopplerJobsServer/Startup.cs
- DopplerJobsServer/appsettings.QA.json
- DopplerJobsServer/appsettings.int.json
- DopplerJobsServer/appsettings.json
Change appsettings and also hidden Hangfire dashboard in QA, PROD and INT environment 
- For now, jobs are executed manually only first of December
> [DAT-65] Update appsettings

- DopplerJobsServer/appsettings.json
> Fix path for key.xml

- DopplerCurrencyJob/Authorization/JwtOptions.cs
- DopplerCurrencyJob/Authorization/TokenServiceCollectionExtensions.cs
- DopplerCurrencyJob/Enums/CurrencyTypeEnum.cs
- DopplerJobTest/CreateSutCurrencyServiceTests.cs
- DopplerJobTest/DopplerCurrencyServiceTests.cs
- DopplerJobTest/Integration/TestServerFixture.cs
- DopplerJobsServer/HangfireAuthorizationFilter.cs
- DopplerJobsServer/Program.cs
- DopplerJobsServer/Startup.cs
Add COP value in enum for insert currency in Doppler database, in additional add exclude code coverage of unnecessary code to tests
> Add Colombia currency

- .dependabot/config.yml
See https://github.com/MakingSense/doppler-jobs/issues/27
Update dependabot package-manager javascript by dotnet:nuget
> Fix dependabot issue

- Doppler.Database/Doppler.Database.csproj
This package is not used and also hasa problem with bot
> Remove unnecessary package

- CrossCutting/CrossCutting.csproj
- DopplerCurrencyJob/Doppler.Currency.Job.csproj
This package is not used in Doppler.Jobs
> Remove unused packages

- DopplerJobsServer/appsettings.qa.json
In the Qa environment, we recreate the production environment with sap data test
> Fix qa environment configs

- CrossCutting/Authorization/JwtTokenGenerator.cs
- DopplerJobTest/TokenGeneratorTests.cs
the issu tag is added with the value true in the generation of the token, the corresponding test is added to
> feat: add issu tag into the token with the value true

- DopplerJobTest/Integration/DopplerCurrencyJobTests.cs
- DopplerJobsServer/appsettings.development.json
- DopplerJobsServer/appsettings.json
We need to add  Colombia currency to send to Sap system and Doppler
> [DAT-206] Add colombia cotization

- CrossCutting/DopplerSapService/Entities/UserBilling.cs
- DopplerBillingJob/Database/DopplerRepository.cs
- DopplerBillingJob/Database/IDopplerRepository.cs
- DopplerBillingJob/DopplerBillingUsJob.cs
- DopplerBillingJob/Settings/DopplerBillingUsJobSettings.cs
- DopplerJobTest/HelperExtension.cs
- DopplerJobTest/Integration/DopplerBillingUsJobTests.cs
- DopplerJobsServer/Startup.cs
- DopplerJobsServer/appsettings.development.json
- DopplerJobsServer/appsettings.json
Create a new job to generate the monthly invoices for the BillingSystem = **'QuickBookUsa'** and send them to SAP US.
**Task:** [DAT-188](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-188)
> feat: generate the monthly invoices for the BillingSystem = 'QuickBookUsa' and send them to SAP US

- CrossCutting/CrossCutting.csproj
- Dockerfile
- Doppler.Database/Doppler.Database.csproj
- DopplerBillingJob/Doppler.Billing.Job.csproj
- DopplerCurrencyJob/Doppler.Currency.Job.csproj
- DopplerJobTest/Doppler.Jobs.Test.csproj
- DopplerJobsServer/Dockerfile
- DopplerJobsServer/Doppler.Jobs.Server.csproj
- DopplerJobsServer/Properties/launchSettings.json
Hi team , we update dotnet 5 and also dependabot dependences
> Update dotnet 5 and dependabot dependences

- CrossCutting/CrossCutting.csproj
- Doppler.Database/Doppler.Database.csproj
- DopplerJobTest/Doppler.Jobs.Test.csproj
- DopplerJobsServer/Doppler.Jobs.Server.csproj
> Update dependabot dependences 

- CrossCutting/CrossCutting.csproj
- Doppler.Database/Doppler.Database.csproj
- DopplerBillingJob/Doppler.Billing.Job.csproj
- DopplerCurrencyJob/Doppler.Currency.Job.csproj
- DopplerJobTest/Doppler.Jobs.Test.csproj
- DopplerJobsServer/Doppler.Jobs.Server.csproj
> chore: Update Dependabot dependeces

- CrossCutting/CrossCutting.csproj
- DopplerBillingJob/Doppler.Billing.Job.csproj
- DopplerCurrencyJob/Doppler.Currency.Job.csproj
- DopplerJobTest/Doppler.Jobs.Test.csproj
- DopplerJobsServer/Doppler.Jobs.Server.csproj
Update Dependabot dependencies
> chore: update dependences

- CrossCutting/CrossCutting.csproj
- DopplerBillingJob/Doppler.Billing.Job.csproj
- DopplerCurrencyJob/Doppler.Currency.Job.csproj
- DopplerJobTest/Doppler.Jobs.Test.csproj
- DopplerJobsServer/Doppler.Jobs.Server.csproj
Update Dependabot dependencies
> chore: Update dependabot

- DopplerJobTest/HelperExtension.cs
- DopplerJobTest/Integration/DopplerFreeTrialFinishesTodayNotificationJobTests.cs
- DopplerJobsServer/Startup.cs
- DopplerJobsServer/appsettings.json
- NotificationsJob/DopplerFreeTrialFinishesTodayNotificationJob.cs
Create a new job to send a notification when free trial expires today.
**Task:** [DAT-750](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-750)
> [DAT-750] - Create a new job to send a notification when free trial expires today

- CrossCutting/CrossCutting.csproj
- CrossCutting/EmailSenderService/Attachment.cs
- CrossCutting/EmailSenderService/EmailNotificationsConfiguration.cs
- CrossCutting/EmailSenderService/IEmailSender.cs
- CrossCutting/EmailSenderService/RelayEmailSender.cs
- CrossCutting/EmailSenderService/RelayEmailSenderSettings.cs
- DopplerJobTest/RelayEmailSenderTest.cs
- DopplerJobsServer/Startup.cs
- DopplerJobsServer/appsettings.development.json
- DopplerJobsServer/appsettings.json
Here we are adding an Email Sender service, and we implement it to send by Relay.
> [DAT-748] - Add Email Sender service

- DopplerJobTest/HelperExtension.cs
- DopplerJobTest/Integration/DopplerFreeTrialExpiredNotificationJobTests.cs
- NotificationsJob/Database/DopplerRepository.cs
- NotificationsJob/Database/IDopplerRepository.cs
- NotificationsJob/DopplerFreeTrialExpiredNotificationJob.cs
Create a new job to send a notification when the free trial has expired.
**Task:** [DAT-751](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-751)
> [DAT-751] - Create a new job to send a notification when the free trial has expired

- DopplerJobsServer/Startup.cs
- DopplerJobsServer/appsettings.json
> feat(jobs): Include the new job

- CrossCutting/EmailSenderService/EmailNotificationsConfiguration.cs
- DopplerJobTest/Integration/DopplerFreeTrialFinishesIn7DaysNotificationJobTests.cs
- DopplerJobsServer/Startup.cs
- DopplerJobsServer/appsettings.development.json
- DopplerJobsServer/appsettings.int.json
- DopplerJobsServer/appsettings.json
- DopplerJobsServer/appsettings.qa.json
- NotificationsJob/DopplerFreeTrialFinishesIn7DaysNotificationJob.cs
Integrate DopplerFreeTrialFinishesIn7DaysNotification Job with EmailSender service.
**Task:** [DAT-749](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-749)
> [DAT-749] - Integrate DopplerFreeTrialFinishesIn7DaysNotification Job with EmailSender service

- CrossCutting/EmailSenderService/EmailNotificationsConfiguration.cs
- DopplerJobTest/Integration/DopplerFreeTrialFinishesTodayNotificationJobTests.cs
- DopplerJobsServer/appsettings.json
- NotificationsJob/DopplerFreeTrialFinishesTodayNotificationJob.cs
Integrate DopplerFreeTrialFinishesIn7DaysNotification Job with EmailSender service.
**Task:** [DAT-754](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-754)
> feat(jobs): Integrate DopplerFreeTrialFinishesIn7DaysNotification Job with EmailSender service

- CrossCutting/EmailSenderService/EmailNotificationsConfiguration.cs
- DopplerJobTest/Integration/DopplerFreeTrialExpiredNotificationJobTests.cs
- DopplerJobsServer/appsettings.development.json
- DopplerJobsServer/appsettings.json
- NotificationsJob/DopplerFreeTrialExpiredNotificationJob.cs
Integrate DopplerFreeTrialExpiredNotification Job with EmailSender service
**Task:** [DAT-755](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-755)
> [DAT-755] - Integrate DopplerFreeTrialExpiredNotification Job with EmailSender service

- DopplerJobsServer/appsettings.development.json
- DopplerJobsServer/appsettings.int.json
- DopplerJobsServer/appsettings.json
- DopplerJobsServer/appsettings.qa.json
Update template ids for the environments
Task: [DAT-756](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-756)
> [DAT-756] - Update template ids for the environments

- NotificationsJob/Database/DopplerRepository.cs
Update queries to get information about the user
> [No-Ticket] - Update queries to get information about the user

- DopplerJobTest/Integration/DopplerFreeTrialFinishesIn7DaysNotificationJobTests.cs
- DopplerJobTest/Integration/DopplerFreeTrialFinishesTodayNotificationJobTests.cs
- NotificationsJob/Database/DopplerRepository.cs
- NotificationsJob/DopplerFreeTrialFinishesIn7DaysNotificationJob.cs
- NotificationsJob/DopplerFreeTrialFinishesTodayNotificationJob.cs
> [No-Ticket] - Update logic to send email

- DopplerJobsServer/appsettings.json
Update relay account and templates used to send email from relay
**Task:** [DAT-806](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-806)
> [DAT-806] - Update relay account and templates used to send email from relay

- DopplerJobsServer/appsettings.json
Change time of the expiration notifications
> [No-Ticket] change time

- DopplerJobsServer/appsettings.json
Change time of expiration notification
> [No-Ticket] Change time of expiration notification

- Doppler.Database/DbConnectionFactory.cs
- Doppler.Database/DopplerDatabaseSettings.cs
- DopplerJobsServer/Startup.cs
- DopplerJobsServer/appsettings.development.json
- DopplerJobsServer/appsettings.int.json
- DopplerJobsServer/appsettings.json
- DopplerJobsServer/appsettings.qa.json
Jira Ticket: [DAT-1424](https://makingsense.atlassian.net/browse/DAT-1424)
Modify project to use only the encrypted password of the appsettings.Secret files instead of the entire connection string
[DAT-1424]: https://makingsense.atlassian.net/browse/DAT-1424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Dat 1424 use encrypted db password

- DopplerBillingJob/Database/DopplerRepository.cs
Resolve timeout issue with billing store procedures
Task: [DAT-1629](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1629)
[DAT-1629]: https://makingsense.atlassian.net/browse/DAT-1629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DAT-1629] fix: Resolve timeout issue with billing store procedures

- CrossCutting/CrossCutting.csproj
- CrossCutting/DopplerSapService/Entities/AdditionalService.cs
- CrossCutting/DopplerSapService/Entities/Pack.cs
- CrossCutting/DopplerSapService/Entities/UserBilling.cs
- CrossCutting/DopplerSapService/Enum/AdditionalServiceTypeEnum.cs
- Dockerfile
- Doppler.Database/Doppler.Database.csproj
- DopplerBillingJob/Database/DopplerRepository.cs
- DopplerBillingJob/Doppler.Billing.Job.csproj
- DopplerBillingJob/Entities/BillingCredit.cs
- DopplerBillingJob/Entities/LandingPlanUser.cs
- DopplerBillingJob/Entities/UserAddOn.cs
- DopplerBillingJob/Enums/AddOnTypeEnum.cs
- DopplerCurrencyJob/Doppler.Currency.Job.csproj
- DopplerJobTest/Doppler.Jobs.Test.csproj
- DopplerJobsServer/Dockerfile
- DopplerJobsServer/Doppler.Jobs.Server.csproj
- NotificationsJob/Doppler.Notifications.Job.csproj
Integrate with addons
Task: [DAT-1935](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-1935)
[DAT-1935]: https://makingsense.atlassian.net/browse/DAT-1935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DAT-1935] - Integrate with addons

- CrossCutting/DopplerSapService/DopplerSapService.cs
- CrossCutting/DopplerSapService/Entities/AdditionalService.cs
- CrossCutting/DopplerSapService/Entities/BillingRequest.cs
- CrossCutting/DopplerSapService/IDopplerSapService.cs
- DopplerBillingJob/Database/DopplerRepository.cs
- DopplerBillingJob/Database/IDopplerRepository.cs
- DopplerBillingJob/DopplerBillingJob.cs
- DopplerBillingJob/DopplerBillingUsJob.cs
- DopplerBillingJob/Entities/BillingCredit.cs
- DopplerBillingJob/Entities/ChatPlanUser.cs
- DopplerBillingJob/Entities/UserBilling.cs
- DopplerBillingJob/Enums/AddOnTypeEnum.cs
- DopplerBillingJob/Mappers/BillingMapper.cs
- DopplerBillingJob/Mappers/IBillingMapper.cs
- DopplerJobTest/Integration/DopplerBillingJobTests.cs
- DopplerJobTest/Integration/DopplerBillingUsJobTests.cs
- DopplerJobsServer/Startup.cs
Supports conversations plan in the monthly process
**Task:** [DAT-2148](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2148)
[DAT-2148]: https://makingsense.atlassian.net/browse/DAT-2148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DAT-2148] - Supports conversations plan in the montly process

- CrossCutting/DopplerSapService/Entities/AdditionalService.cs
- DopplerBillingJob/Database/DopplerRepository.cs
- DopplerBillingJob/Database/IDopplerRepository.cs
- DopplerBillingJob/Entities/ChatPlanUser.cs
- DopplerBillingJob/Enums/AccountTypeEnum.cs
- DopplerBillingJob/Mappers/BillingMapper.cs
- DopplerBillingJob/Mappers/IBillingMapper.cs
Support montly addosn for the cms
Task: [DAT-2183](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2183)
[DAT-2183]: https://makingsense.atlassian.net/browse/DAT-2183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DAT-2183] - Support montly addosn for the cms

- CrossCutting/DopplerSapService/Entities/AdditionalService.cs
- DopplerBillingJob/Database/DopplerRepository.cs
- DopplerBillingJob/Database/IDopplerRepository.cs
- DopplerBillingJob/Entities/User.cs
- DopplerBillingJob/Mappers/BillingMapper.cs
- DopplerJobsServer/appsettings.int.json
Send user email in the additional services to sap
**Task:** [DAT-2243](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2243)
[DAT-2243]: https://makingsense.atlassian.net/browse/DAT-2243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DAT-2243] - Send user email in the additional services to sap

- CrossCutting/DopplerSapService/Entities/AdditionalService.cs
- CrossCutting/DopplerSapService/Enum/AdditionalServiceTypeEnum.cs
- DopplerBillingJob/Database/DopplerRepository.cs
- DopplerBillingJob/Database/IDopplerRepository.cs
- DopplerBillingJob/Entities/OnSitePlanUser.cs
- DopplerBillingJob/Entities/UserBilling.cs
- DopplerBillingJob/Enums/AddOnTypeEnum.cs
- DopplerBillingJob/Mappers/BillingMapper.cs
Support onsite plan in the monthly process
**Task:** [DAT-2256](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2256)
[DAT-2256]: https://makingsense.atlassian.net/browse/DAT-2256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DAT-2256] - Support onsite plan in the monthly process

- CrossCutting/DopplerPopUpHubService/DopplerPopUpHubService.cs
- CrossCutting/DopplerPopUpHubService/IDopplerPopUpHubService.cs
- CrossCutting/DopplerPopUpHubService/Settings/DopplerPopUpHubServiceConfiguration.cs
- Dockerfile
- Doppler.Jobs.sln
- DopplerJobsServer/Doppler.Jobs.Server.csproj
- DopplerJobsServer/Startup.cs
- DopplerJobsServer/appsettings.development.json
- DopplerJobsServer/appsettings.int.json
- DopplerJobsServer/appsettings.json
- DopplerJobsServer/appsettings.qa.json
- SurplusAddOnJob/Database/DopplerRepository.cs
- SurplusAddOnJob/Database/IDopplerRepository.cs
- SurplusAddOnJob/Doppler.SurplusAddOn.Job.csproj
- SurplusAddOnJob/DopplerSurplusOnSiteJob.cs
- SurplusAddOnJob/Entities/OnSiteAddon.cs
- SurplusAddOnJob/Entities/OnSitePlan.cs
- SurplusAddOnJob/Enums/AddOnTypeEnum.cs
- SurplusAddOnJob/Utils/DateTimeProvider.cs
- SurplusAddOnJob/Utils/IDateTimeProvider.cs
Add new job to get surplus impressions for the onsite plan.
**Task:** [DAT-2344](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2344)
[DAT-2344]: https://makingsense.atlassian.net/browse/DAT-2344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DAT-2344] - Add new job to get surplus impressions for the onsite plan

- DopplerBillingJob/Mappers/BillingMapper.cs
fix issue when send surplus for the onsite
> fix issue when send surplus for the onsite

- CrossCutting/DopplerBeplicService/DopplerBeplicService.cs
- CrossCutting/DopplerBeplicService/IDopplerBeplicService.cs
- CrossCutting/DopplerBeplicService/Settings/DopplerBeplicServiceConfiguration.cs
- DopplerJobsServer/Startup.cs
- DopplerJobsServer/appsettings.development.json
- DopplerJobsServer/appsettings.int.json
- DopplerJobsServer/appsettings.json
- DopplerJobsServer/appsettings.qa.json
- SurplusAddOnJob/Database/DopplerRepository.cs
- SurplusAddOnJob/Database/IDopplerRepository.cs
- SurplusAddOnJob/DopplerSurplusConversationsJob.cs
- SurplusAddOnJob/Entities/SurplusAddOn.cs
- SurplusAddOnJob/Entities/UserAddOn.cs
Add new job to support the surplus conversation.
**Task:** [DAT-2168](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2168)
[DAT-2168]: https://makingsense.atlassian.net/browse/DAT-2168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DAT-2168] - Add new job to support the surplus conversations

- DopplerBillingJob/Database/DopplerRepository.cs
- DopplerBillingJob/Database/IDopplerRepository.cs
- DopplerBillingJob/Entities/SurplusAddOn.cs
- DopplerBillingJob/Mappers/BillingMapper.cs
Update logic to calculate the addon surplus when is cm user
> [no-task] - Update logic to calculate the addon surplus when is cm user

- SurplusAddOnJob/DopplerSurplusConversationsJob.cs
Test in prod environment the integration with beplic api
> [no-task] Test in prod environment the integration with beplic api

- DopplerJobsServer/appsettings.json
Change url fro the prod environment
> [no-task] - Change url fro the prod environment

- DopplerJobsServer/appsettings.json
Update onsite url for the prod environment
> [no-task] Update onsite url for the prod environment

- CrossCutting/DopplerSapService/Entities/AdditionalService.cs
- CrossCutting/DopplerSapService/Enum/AdditionalServiceTypeEnum.cs
- DopplerBillingJob/Database/DopplerRepository.cs
- DopplerBillingJob/Database/IDopplerRepository.cs
- DopplerBillingJob/Entities/AddOnPlanUser.cs
- DopplerBillingJob/Entities/UserBilling.cs
- DopplerBillingJob/Enums/AddOnTypeEnum.cs
- DopplerBillingJob/Mappers/BillingMapper.cs
Supports to send to sap the push notifications plans.
**Task:** [DAT-2429](https://makingsense.atlassian.net/browse/DAT-2429)
[DAT-2429]: https://makingsense.atlassian.net/browse/DAT-2429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DAT-2429] - Supports to send to sap the push notifications plans

- DopplerBillingJob/Extensions/Parse.cs
- DopplerBillingJob/Mappers/BillingMapper.cs
- DopplerJobsServer/appsettings.json
Fix issue when send surplus to sap
**Task:** [DAT-2512](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2512)
[DAT-2512]: https://makingsense.atlassian.net/browse/DAT-2512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DAT-2512] - Fix issue when send surplus to sap

- DopplerCancelAccountJob/Database/DopplerRepository.cs
- DopplerCancelAccountJob/Database/IDopplerRepository.cs
- DopplerCancelAccountJob/DopplerCancelAccountWithScheduleCancellationJob.cs
- DopplerCancelAccountJob/Entities/AccountCancellationReason.cs
- DopplerCancelAccountJob/Entities/User.cs
- DopplerCancelAccountJob/Entities/UserAccountCancellationReason.cs
Update logic to cancel account
> [no-task] - Update logic to cancel account
